### ISSUE TITLE
Javascript errors when following install instructions

### ISSUE THREAD

**Issue by Einenlum** [simjanos-dev/LinguaCafe#47]
Hi there.

I followed the instructions to install on Linux (on `main`, commit `f120a47`) and the page `http://localhost:9191/login` is blank with some console errors:

On Firefox:

```
TypeError: c.primary is undefined
TypeError: t.$vuetify.theme.currentTheme is undefined
```

On Brave:

```
TypeError: Cannot read properties of undefined (reading 'base')
TypeError: Cannot read properties of undefined (reading 'background')
```

**Comment by systemcrash** [comment]
Just observations, but these likely stem from using node-14. While an update to at least node-18 might resolve some bugs, it will probably also bring some new ones :)

**Comment by simjanos-dev** [comment]
@systemcrash I've had no idea what could cause this. I think node 14 comes from some weird issue from back when I ran LinguaCafe in a virtual machine, and couldn't install newer one for some reasons. I'll try updating to a newer version and check if it cause any new bugs.

**Comment by simjanos-dev** [comment]
Hi @Einenlum!

I've updated to node v20 on the dev branch, and it also has a new docker process since that. 

You can test it out on the dev branch by following these steps if you would like to (this is just for testing, please do not use it as a production version). It will also be in the main branch in 2 weeks probably.

Step 1: Run this command
`git clone -b deploy https://github.com/simjanos-dev/LinguaCafe.git linguacafe`

Step 2: Modify the `docker-compose.yml` file, and replace the :main tags with :dev in these 2 lines:
```
image: ghcr.io/simjanos-dev/linguacafe-webserver:main
image: ghcr.io/simjanos-dev/linguacafe-python-service:main
```

Step 3: run this command from the directory of linguacafe:
`chmod 777 -R ./ && docker compose up -d`

If the node update did not solve your problem I'll investigate it further.

**Comment by Einenlum** [comment]
Hi @simjanos-dev, thanks for your efforts!

Unfortunately it has not solved my issues :crying_cat_face: 

I followed the instructions:

```shell
/tmp  git clone -b deploy https://github.com/simjanos-dev/LinguaCafe.git linguacafe
Cloning into 'linguacafe'...
remote: Enumerating objects: 3474, done.
remote: Counting objects: 100% (1021/1021), done.
remote: Compressing objects: 100% (379/379), done.
remote: Total 3474 (delta 679), reused 917 (delta 614), pack-reused 2453
Receiving objects: 100% (3474/3474), 88.57 MiB | 22.13 MiB/s, done.
Resolving deltas: 100% (2273/2273), done.
/tmp cd linguacafe 
/tmp/linguacafe (deploy ✔) vim docker-compose.yml 
/tmp/linguacafe (deploy ✗)  chmod 777 -R ./ && docker compose up -d
[+] Running 29/29
 ✔ python 6 layers [⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                                          27.4s 
   ✔ 29202e855b20 Already exists                                                                                                                                                                             0.0s 
   ✔ 7f4e8deab500 Pull complete                                                                                                                                                                              0.3s 
   ✔ 1c8a0631c296 Pull complete                                                                                                                                                                              3.3s 
   ✔ 890250996c0d Pull complete                                                                                                                                                                              2.4s 
   ✔ a01920768240 Pull complete                                                                                                                                                                             19.1s 
   ✔ 66fcf387b7b6 Pull complete                                                                                                                                                                              2.9s 
 ✔ webserver 21 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                       29.2s 
   ✔ 2f44b7a888fa Already exists                                                                                                                                                                             0.0s 
   ✔ 3a95dcec6035 Already exists                                                                                                                                                                             0.0s 
   ✔ e22afa33f327 Already exists                                                                                                                                                                             0.0s 
   ✔ 1aa61ea11ee8 Already exists                                                                                                                                                                             0.0s 
   ✔ ea67ae2bde33 Pull complete                                                                                                                                                                              5.4s 
   ✔ ff5356c6468f Pull complete                                                                                                                                                                              3.7s 
   ✔ 5e91cb51e886 Pull complete                                                                                                                                                                              4.2s 
   ✔ 935e88b21d5f Pull complete                                                                                                                                                                              5.7s 
   ✔ 8202e883ada1 Pull complete                                                                                                                                                                              5.9s 
   ✔ be40d3507d33 Pull complete                                                                                                                                                                              7.1s 
   ✔ 5fac4c1a6ab6 Pull complete                                                                                                                                                                              6.3s 
   ✔ 03fcb105f703 Pull complete                                                                                                                                                                              6.8s 
   ✔ 87c6b0d7fa4d Pull complete                                                                                                                                                                              7.2s 
   ✔ 06c8d1082aa8 Pull complete                                                                                                                                                                              8.5s 
   ✔ b94dcaa5c261 Pull complete                                                                                                                                                                             12.2s 
   ✔ 887def2538bc Pull complete                                                                                                                                                                              9.1s 
   ✔ 2b864acdfbbc Pull complete                                                                                                                                                                              9.6s 
   ✔ 42f2dd4b4ab3 Pull complete                                                                                                                                                                             10.1s 
   ✔ 00e19ce2abea Pull complete                                                                                                                                                                             19.3s 
   ✔ d993e08b3872 Pull complete                                                                                                                                                                             16.3s 
   ✔ 83ee2fe545e5 Pull complete                                                                                                                                                                             20.2s 
[+] Running 3/3
 ✔ Container linguacafe-database        Started                                                                                                                                                              0.1s 
 ✔ Container linguacafe-python-service  Started                                                                                                                                                              0.1s 
 ✔ Container linguacafe-webserver       Started                                                                                                                                                              0.1s 
/tmp/linguacafe (deploy ✗) docker-compose ps
NAME                        IMAGE                                                COMMAND                  SERVICE     CREATED         STATUS         PORTS
linguacafe-database         mysql:8.0                                            "docker-entrypoint.s…"   mysql       3 seconds ago   Up 2 seconds   33060/tcp, 0.0.0.0:3308->3306/tcp, :::3308->3306/tcp
linguacafe-python-service   ghcr.io/simjanos-dev/linguacafe-python-service:dev   "/app/manage.py runs…"   python      3 seconds ago   Up 2 seconds   
linguacafe-webserver        ghcr.io/simjanos-dev/linguacafe-webserver:dev        "/var/www/html/entry…"   webserver   3 seconds ago   Up 2 seconds   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp, 0.0.0.0:9191->80/tcp, :::9191->80/tcp
```

I still have these errors on Firefox:

![f1](https://github.com/simjanos-dev/LinguaCafe/assets/5675200/a8e47012-9a06-4929-b64c-68a02613a2d2)
![f2](https://github.com/simjanos-dev/LinguaCafe/assets/5675200/e520f993-14dd-4b4e-9f6c-7d348546deb5)

And these errors on Chromium:

![c](https://github.com/simjanos-dev/LinguaCafe/assets/5675200/dcb3f80e-5220-40cb-af5f-493512790077)

**Comment by simjanos-dev** [comment]
This is so weird. Javascript is built by github and is inside the docker image now, and it seems to be not a browser problem. Also in the latest version all js and css dependencies are downloaded, so there is nothing that needs internet connection.

Could you please run this command while your server is running, and see if it has any errors? 

`docker exec -ti linguacafe-webserver npm run`

Thank you so much for giving detailed report with images and logs! This helps a lot.

**Comment by Einenlum** [comment]
Going to check when I'm home! Thanks for your implication on this 🙂

**Comment by simjanos-dev** [comment]
@sergiolaverde0 Any idea what can cause this? I don't really have any. If the npm builds successfully on github, it should work the same for everyone, except if there are browser compatibility issues.

**Comment by sergiolaverde0** [comment]
I don't have a clue either. It happened to this specific user in two versions of Node released years apart and in conventional, widespread browsers that I assume have been updated at least once in the last decade.

Only thing I can think of is that if the user has an overly aggressive privacy configuration, try relaxing it a little, this service has no telemetry at all.

**Comment by simjanos-dev** [comment]
Now that you mention it, there is a cookie that stores the selected theme's name, which the error message mentions. The only way it could break, is that if the cookie exist, but contains corrupted data.

**Comment by sergiolaverde0** [comment]
If this two weeks old report that spans three different releases is solved by literally deleting the cookies I'm gonna go postal.

**Comment by Einenlum** [comment]
Ok this is super weird. It seems indeed related.

On Chromium it works (I said chromium before but it was actually brave: sorry, that was misleading).

![chromium](https://github.com/simjanos-dev/LinguaCafe/assets/5675200/2140a693-fd76-4162-a7dd-dbbdd8765803)

It still doesn't work on Brave, but every protection against tracking or adblock is disabled.

![brave](https://github.com/simjanos-dev/LinguaCafe/assets/5675200/9372b0a3-89be-404a-bbf8-8b061292cd58)

Same for Firefox:

![firefox](https://github.com/simjanos-dev/LinguaCafe/assets/5675200/63c4dfa5-2f24-4f24-8bce-e44e20907015)

I always disable my adblock and tracking protection extensions when I'm on localhost.

What's super weird is that everything seems to be fetched correctly in the network tab.

Brave:

![brave200](https://github.com/simjanos-dev/LinguaCafe/assets/5675200/d726d10e-527c-4fcf-b8d8-1898b96fc344)

Firefox:

![firefox200](https://github.com/simjanos-dev/LinguaCafe/assets/5675200/928411bc-752a-44b4-9991-3e9e80550457)

**Comment by simjanos-dev** [comment]
It is weird. I don't think I can help with it, it seems like it is a browser related issue. But I would love to find out what causes this. LinguaCafe uses simple cookies which are required for it to work, but I don't think there's anything else privacy related that can mess it up. I tested it on `121.0 (64-bit)`  firefox, it works well.

What happens on firefox if you try it in private mode?
